## My First Notebook

In [ ]:
import pandas as pd

In [ ]:
pip install xlrd

Requirement already satisfied: xlrd in c:\users\sharon\anaconda3\lib\site-packages (2.0.1)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd

serial_number = "控制性低強度回填材料"

# read in dataframe
#data = pd.read_excel("C:/Users/Sharon/Desktop/jupyter notebook/114049.xls")
# filter dataframe with a str.contains method.

In [ ]:
# to read just one sheet to dataframe:
df = pd.read_excel("C:/Users/Sharon/Desktop/jupyter notebook/114A056.xls", sheet_name="標單詳細表")

In [ ]:
df

,新竹市政府,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,詳細價目表[標單],NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,工程名稱,114年度新竹市以西水利工程及道路排水改善工程(開口契約),NaN,NaN,會計科目,NaN,NaN
...,...,...,...,...,...,...,...
301,2,營業稅(上列各項之和*5%),式,1,NaN,0,NaN
302,NaN,小計二,NaN,NaN,NaN,NaN,NaN
303,NaN,發包工程費(一+二),NaN,NaN,NaN,NaN,NaN
304,NaN,單價乘以預估數量之和,NaN,NaN,NaN,NaN,NaN
305,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.columns

Index(['新竹市政府', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6'],
      dtype='object')

In [ ]:
df.iloc[:,1]

0                                NaN
1                                NaN
2                                NaN
3                                NaN
4      114年度新竹市以西水利工程及道路排水改善工程(開口契約)
                   ...
301                   營業稅(上列各項之和*5%)
302                              小計二
303                       發包工程費(一+二)
304                       單價乘以預估數量之和
305                              NaN
Name: Unnamed: 1, Length: 306, dtype: object

In [ ]:
df_brick = df[df.iloc[:,1].str.contains('磚',na=False)]
df_CLSM=df[df.iloc[:,1].str.contains('控制性低強度回填材料',na=False)]
df_stone=df[df.iloc[:,1].str.contains('緣石',na=False)]
df_AC=df[df.iloc[:,1].str.contains('瀝青混凝土',na=False)]
df_graded=df[df.iloc[:,1].str.contains('級配',na=False)]

In [ ]:
df_AC

,新竹市政府,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
10,2,機械切割，瀝青混凝土,M,100,NaN,0,"0222030101,*"
22,11,瀝青混凝土面層刨除,M3,30,NaN,0,"0296100003,*"
25,14,再生瀝青混凝土鋪面，(密級配，30%回收,M3,25,NaN,0,"0296610003,新粒"
28,15,再生瀝青混凝土鋪面，(粗級配，30%回收,M3,10,NaN,0,"0296630003,*"
30,16,瀝青混凝土舖面,M3,10,NaN,0,"0274200003,(新"
282,NaN,建築類檢驗，瀝青混凝土黏滯度試驗,NaN,NaN,NaN,0,萃取)

In [ ]:
print("磚:",df_brick.iloc[:,3].sum(),"CLSM:",df_CLSM.iloc[:,3].sum(),"緣石:",df_stone.iloc[:,3].sum(),"瀝青混凝土:",df_AC.iloc[:,3].sum(),"級配:",df_graded.iloc[:,3].sum())

磚: 0 CLSM: 60 緣石: 0 瀝青混凝土: 175 級配: 85

In [ ]:
filter_df = df[(df.iloc[:,1].str.contains('控制性低強度回填材料')) | (df.iloc[:,1].str.contains('磚'))| (df.iloc[:,1].str.contains('緣石'))|(df.iloc[:,1].str.contains('瀝青混凝土'))|(df.iloc[:,1].str.contains('級配'))|(df.iloc[:,1].str.contains('水泥'))|(df.iloc[:,1].str.contains('級配'))]

filter_df

,新竹市政府,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
9,1,機械切割，水泥混凝土,M,100,NaN,0,"0222030201,*"
10,2,機械切割，瀝青混凝土,M,100,NaN,0,"0222030101,*"
22,11,瀝青混凝土面層刨除,M3,30,NaN,0,"0296100003,*"
25,14,再生瀝青混凝土鋪面，(密級配，30%回收,M3,25,NaN,0,"0296610003,新粒"
28,15,再生瀝青混凝土鋪面，(粗級配，30%回收,M3,10,NaN,0,"0296630003,*"
30,16,瀝青混凝土舖面,M3,10,NaN,0,"0274200003,(新"
32,17,級配粒料底層，碎石級配，鋪設及滾壓,M3,50,NaN,0,"0272610053,*"
33,18,控制性低強度回填材料(CLSM回填處理),M3,50,NaN,0,"0337700003A,#,*"
54,33,控制性低強度回填材料(現地土壤拌合改良,M3,10,NaN,0,"0337700003B,#,*"
60,36,水泥砂漿，1:3,M3,50,NaN,0,"0406130003,*"
88,57,水泥漆，一底二度，粉刷,M2,50,NaN,0,"0991200002,#,*"
282,NaN,建築類檢驗，瀝青混凝土黏滯度試驗,NaN,NaN,NaN,0,萃取)

In [ ]:
if

SyntaxError: invalid syntax (4110802630.py, line 1)